// frontend/src/components/settings/RulesSection.tsx
"use client";

import * as React from "react";
import { toast } from "sonner";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Input, Label, FieldHint } from "@/components/ui/Input";
import { TagInput } from "@/components/ui/TagInput";
import { saveSettings } from "@/lib/hooks/useSettings";
import { apiErrorMessage } from "@/lib/api-client";
import type { SettingsResponse } from "@/lib/types";

type Rules = SettingsResponse["rules"];

export function RulesSection({
  settings,
  onSaved,
}: {
  settings: Rules;
  onSaved: () => void;
}) {
  const [form, setForm] = React.useState<Rules>(settings);
  const [saving, setSaving] = React.useState(false);

  // Re-sync local form state when `settings` changes (after a save/refetch)
  // without an Effect — setState during render is React's documented pattern
  // for this, and SWR gives each fetch a new object reference to compare against.
  const [syncedSettings, setSyncedSettings] = React.useState(settings);
  if (settings !== syncedSettings) {
    setSyncedSettings(settings);
    setForm(settings);
  }

  function setField<K extends keyof Rules>(key: K, value: Rules[K]) {
    setForm((f) => ({ ...f, [key]: value }));
  }

  async function handleSave() {
    setSaving(true);
    try {
      await saveSettings({ ...form });
      toast.success("Rules saved.");
      onSaved();
    } catch (error) {
      toast.error(apiErrorMessage(error, "Could not save rules."));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Bidding rules</CardTitle>
      </CardHeader>
      <CardContent className="space-y-5">
        <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
          <NumberField
            label="Min budget ($)"
            value={form.min_budget}
            onChange={(v) => setField("min_budget", v)}
          />
          <NumberField
            label="Max proposals"
            value={form.max_proposals}
            onChange={(v) => setField("max_proposals", v)}
          />
          <NumberField
            label="Score cutoff"
            value={form.score_cutoff}
            onChange={(v) => setField("score_cutoff", v)}
            hint="1–10"
          />
          <NumberField
            label="Hourly floor ($/hr)"
            value={form.hourly_floor}
            onChange={(v) => setField("hourly_floor", v)}
          />
          <NumberField
            label="Zero-history budget floor ($)"
            value={form.zero_history_budget_floor}
            onChange={(v) => setField("zero_history_budget_floor", v)}
          />
          <NumberField
            label="Follow up after (days)"
            value={form.followup_days}
            onChange={(v) => setField("followup_days", v)}
          />
        </div>

        <div>
          <Label>Stack keywords</Label>
          <TagInput
            value={form.stack_keywords}
            onChange={(v) => setField("stack_keywords", v)}
            placeholder="Add a keyword and press Enter…"
            testId="stack-keywords-input"
          />
          <FieldHint>Used for scoring context and the Analytics &quot;best job types&quot; chart.</FieldHint>
        </div>

        <div>
          <Label>Red-flag phrases</Label>
          <TagInput
            value={form.red_flag_words}
            onChange={(v) => setField("red_flag_words", v)}
            placeholder="Add a phrase and press Enter…"
            testId="red-flag-words-input"
          />
          <FieldHint>Any brief containing one of these is archived before any AI call runs.</FieldHint>
        </div>

        <div className="flex justify-end">
          <Button onClick={handleSave} loading={saving}>
            Save rules
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function NumberField({
  label,
  value,
  onChange,
  hint,
}: {
  label: string;
  value: number;
  onChange: (v: number) => void;
  hint?: string;
}) {
  return (
    <div>
      <Label>{label}</Label>
      <Input
        type="number"
        value={value}
        onChange={(e) => onChange(Number(e.target.value))}
      />
      {hint && <FieldHint>{hint}</FieldHint>}
    </div>
  );
}

// resources/js/components/settings/RulesSection.vue
<script setup>
import { ref, watch } from "vue";
import { toast } from "vue-sonner";
import Card from "@/components/ui/Card.vue";
import CardHeader from "@/components/ui/CardHeader.vue";
import CardTitle from "@/components/ui/CardTitle.vue";
import CardContent from "@/components/ui/CardContent.vue";
import Button from "@/components/ui/Button.vue";
import Input from "@/components/ui/Input.vue";
import Label from "@/components/ui/Label.vue";
import FieldHint from "@/components/ui/FieldHint.vue";
import TagInput from "@/components/ui/TagInput.vue";
import { saveSettings } from "@/composables/useSettings";
import { apiErrorMessage } from "@/lib/api-client";

const props = defineProps({ settings: { type: Object, required: true } });
const emit = defineEmits(["saved"]);

const form = ref({ ...props.settings });
const saving = ref(false);

// Re-sync local form state whenever the settings prop changes (after a save/refetch).
watch(
  () => props.settings,
  (value) => {
    form.value = { ...value };
  },
);

async function handleSave() {
  saving.value = true;
  try {
    await saveSettings({ ...form.value });
    toast.success("Rules saved.");
    emit("saved");
  } catch (error) {
    toast.error(apiErrorMessage(error, "Could not save rules."));
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Bidding rules</CardTitle>
    </CardHeader>
    <CardContent class="space-y-5">
      <div class="grid grid-cols-2 gap-4 sm:grid-cols-3">
        <div>
          <Label>Min budget ($)</Label>
          <Input type="number" v-model.number="form.min_budget" />
        </div>
        <div>
          <Label>Max proposals</Label>
          <Input type="number" v-model.number="form.max_proposals" />
        </div>
        <div>
          <Label>Score cutoff</Label>
          <Input type="number" v-model.number="form.score_cutoff" />
          <FieldHint>1–10</FieldHint>
        </div>
        <div>
          <Label>Hourly floor ($/hr)</Label>
          <Input type="number" v-model.number="form.hourly_floor" />
        </div>
        <div>
          <Label>Zero-history budget floor ($)</Label>
          <Input type="number" v-model.number="form.zero_history_budget_floor" />
        </div>
        <div>
          <Label>Follow up after (days)</Label>
          <Input type="number" v-model.number="form.followup_days" />
        </div>
        <div>
          <Label>Max posting age for AI scoring (days)</Label>
          <Input type="number" v-model.number="form.max_posted_age_days" />
          <FieldHint>Older postings are archived without an AI call — they stay visible, just unscored.</FieldHint>
        </div>
      </div>

      <div>
        <Label>Stack keywords</Label>
        <TagInput v-model="form.stack_keywords" placeholder="Add a keyword and press Enter…" />
        <FieldHint>Used for scoring context and the Analytics "best job types" chart.</FieldHint>
      </div>

      <div>
        <Label>Red-flag phrases</Label>
        <TagInput v-model="form.red_flag_words" placeholder="Add a phrase and press Enter…" />
        <FieldHint>Any brief containing one of these is archived before any AI call runs.</FieldHint>
      </div>

      <div class="flex justify-end">
        <Button @click="handleSave" :loading="saving">Save rules</Button>
      </div>
    </CardContent>
  </Card>
</template>
