// frontend/src/components/analytics/BestJobTypesChart.tsx
"use client";

import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AnalyticsJobType } from "@/lib/types";
import { CHART_CHROME } from "@/lib/chart-colors";
import { EmptyState } from "@/components/ui/EmptyState";
import { BarChart3 } from "lucide-react";

export function BestJobTypesChart({ data }: { data: AnalyticsJobType[] }) {
  if (data.length === 0) {
    return <EmptyState icon={BarChart3} title="Not enough scored leads yet" />;
  }

  return (
    <ResponsiveContainer width="100%" height={Math.max(180, data.length * 38)}>
      <BarChart data={data} layout="vertical" margin={{ top: 4, right: 28, left: 8, bottom: 4 }}>
        <CartesianGrid stroke={CHART_CHROME.grid} horizontal={false} />
        <XAxis
          type="number"
          allowDecimals={false}
          tick={{ fontSize: 11, fill: CHART_CHROME.axis }}
          axisLine={false}
          tickLine={false}
        />
        <YAxis
          type="category"
          dataKey="keyword"
          width={100}
          tick={{ fontSize: 12, fill: CHART_CHROME.textPrimary }}
          axisLine={false}
          tickLine={false}
        />
        <Tooltip
          cursor={{ fill: "rgba(10,102,194,0.06)" }}
          contentStyle={{ borderRadius: 8, border: `1px solid ${CHART_CHROME.border}`, fontSize: 12 }}
          formatter={(value) => [`${value} lead${value === 1 ? "" : "s"}`, "Matching brief"]}
        />
        <Bar dataKey="count" fill="#0A66C2" radius={[0, 4, 4, 0]} barSize={16} />
      </BarChart>
    </ResponsiveContainer>
  );
}

// resources/js/components/analytics/BestJobTypesChart.vue
<script setup>
import { computed } from "vue";
import { Bar } from "vue-chartjs";
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Tooltip } from "chart.js";
import { BarChart3 } from "@lucide/vue";
import { CHART_CHROME } from "@/lib/chart-colors";
import EmptyState from "@/components/ui/EmptyState.vue";

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip);

const props = defineProps({ data: { type: Array, required: true } });

const chartData = computed(() => ({
  labels: props.data.map((d) => d.keyword),
  datasets: [
    {
      data: props.data.map((d) => d.count),
      backgroundColor: "#0A66C2",
      borderRadius: 4,
      barThickness: 16,
    },
  ],
}));

const chartOptions = {
  indexAxis: "y",
  responsive: true,
  maintainAspectRatio: false,
  scales: {
    x: {
      beginAtZero: true,
      ticks: { precision: 0, font: { size: 11 }, color: CHART_CHROME.axis },
      grid: { color: CHART_CHROME.grid },
    },
    y: {
      ticks: { font: { size: 12 }, color: CHART_CHROME.textPrimary },
      grid: { display: false },
    },
  },
  plugins: {
    legend: { display: false },
    tooltip: {
      backgroundColor: "#fff",
      titleColor: CHART_CHROME.textPrimary,
      bodyColor: CHART_CHROME.textPrimary,
      borderColor: CHART_CHROME.border,
      borderWidth: 1,
      cornerRadius: 8,
      callbacks: {
        label: (ctx) => `${ctx.parsed.x} lead${ctx.parsed.x === 1 ? "" : "s"} matching brief`,
      },
    },
  },
};

const height = computed(() => Math.max(180, props.data.length * 38));
</script>

<template>
  <EmptyState v-if="data.length === 0" :icon="BarChart3" title="Not enough scored leads yet" />
  <div v-else :style="{ height: `${height}px` }">
    <Bar :data="chartData" :options="chartOptions" />
  </div>
</template>
