// frontend/src/app/(dashboard)/settings/page.tsx
"use client";

import { useSettings } from "@/lib/hooks/useSettings";
import { AuthGuard } from "@/components/layout/AuthGuard";
import { PageContainer } from "@/components/layout/Rails";
import { Skeleton } from "@/components/ui/Skeleton";
import { AiSection } from "@/components/settings/AiSection";
import { VollnaSection } from "@/components/settings/VollnaSection";
import { OpenClawSection } from "@/components/settings/OpenClawSection";
import { WhatsAppSection } from "@/components/settings/WhatsAppSection";
import { RulesSection } from "@/components/settings/RulesSection";

function SettingsContent() {
  const { settings, isLoading, mutate } = useSettings();

  if (isLoading || !settings) {
    return (
      <PageContainer className="max-w-[760px] space-y-4">
        <Skeleton className="h-7 w-40" />
        {Array.from({ length: 4 }).map((_, i) => (
          <Skeleton key={i} className="h-48 w-full" />
        ))}
      </PageContainer>
    );
  }

  return (
    <PageContainer className="max-w-[760px] space-y-4">
      <div>
        <h1 className="text-xl font-semibold text-text-primary">Settings</h1>
        <p className="text-sm text-text-secondary">
          API keys, tokens, and bidding rules — nothing here is stored in .env.
        </p>
      </div>
      <AiSection settings={settings.ai} onSaved={() => mutate()} />
      <VollnaSection settings={settings.vollna} onSaved={() => mutate()} />
      <OpenClawSection settings={settings.openclaw} onSaved={() => mutate()} />
      <WhatsAppSection settings={settings.whatsapp} onSaved={() => mutate()} />
      <RulesSection settings={settings.rules} onSaved={() => mutate()} />
    </PageContainer>
  );
}

export default function SettingsPage() {
  return (
    <AuthGuard adminOnly>
      <SettingsContent />
    </AuthGuard>
  );
}

// resources/js/pages/Settings.vue
<script setup>
import { useSettings } from "@/composables/useSettings";
import PageContainer from "@/components/layout/PageContainer.vue";
import Skeleton from "@/components/ui/Skeleton.vue";
import DiagnosticsSection from "@/components/settings/DiagnosticsSection.vue";
import VollnaSection from "@/components/settings/VollnaSection.vue";
import OpenClawSection from "@/components/settings/OpenClawSection.vue";
import WhatsAppSection from "@/components/settings/WhatsAppSection.vue";
import MailSection from "@/components/settings/MailSection.vue";
import RulesSection from "@/components/settings/RulesSection.vue";

const { settings, isLoading, refetch } = useSettings();
</script>

<template>
  <PageContainer v-if="isLoading || !settings" class="max-w-[760px] space-y-4">
    <Skeleton class="h-7 w-40" />
    <Skeleton v-for="i in 5" :key="i" class="h-48 w-full" />
  </PageContainer>

  <PageContainer v-else class="max-w-[760px] space-y-4">
    <div>
      <h1 class="text-xl font-semibold text-text-primary">Settings</h1>
      <p class="text-sm text-text-secondary">
        API keys, tokens, and bidding rules — nothing here is stored in .env.
      </p>
    </div>
    <DiagnosticsSection />
    <VollnaSection :settings="settings.vollna" @saved="refetch" />
    <OpenClawSection :settings="settings.openclaw" @saved="refetch" />
    <WhatsAppSection :settings="settings.whatsapp" @saved="refetch" />
    <MailSection :settings="settings.mail" @saved="refetch" />
    <RulesSection :settings="settings.rules" @saved="refetch" />
  </PageContainer>
</template>
